/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registerform;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.logging.Logger; 
import java.util.logging.Level; 
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.border.Border;
import loginform.My_CNX;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import loginform.login;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.text.SimpleDateFormat;


/**
 *
 * @author 63966
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setLocationRelativeTo(null); // center the form
        
        // Create the existing border
        Border field_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);

        // Define the padding size (e.g., 5 pixels)
        int paddingSize = 5;

        // Create a CompoundBorder to add padding to the existing border
        Border paddedBorder = BorderFactory.createCompoundBorder(
            field_border,
            BorderFactory.createEmptyBorder(paddingSize, paddingSize, paddingSize, paddingSize)
        );

        // Apply the padded border to your components
        jTextField_FirstName.setBorder(paddedBorder);
        jTextField_LastName.setBorder(paddedBorder);
        jTextField_PhoneNum.setBorder(paddedBorder);
        jDateChooser.setBorder(paddedBorder);
        jTextField_Country.setBorder(paddedBorder);
        jTextField_Username.setBorder(paddedBorder);
        jTextField_Email.setBorder(paddedBorder);
        jPasswordField_1.setBorder(paddedBorder);
        jPasswordField_2.setBorder(paddedBorder);
        
        // Create a ButtonGroup
        ButtonGroup bg = new ButtonGroup();
 
        bg.add(jRadioButton_Male);
        bg.add(jRadioButton_Female);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1left = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2right = new javax.swing.JPanel();
        jLabel1Close = new javax.swing.JLabel();
        jLabel2Min = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3HyperlinkSignin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Country = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField_1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField_2 = new javax.swing.JPasswordField();
        jButton_Register = new javax.swing.JButton();
        MovePanel = new javax.swing.JPanel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_Female = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_PhoneNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1left.setBackground(new java.awt.Color(121, 6, 186));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/v2osk-In4XVKhYaiI-unsplash.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1leftLayout = new javax.swing.GroupLayout(jPanel1left);
        jPanel1left.setLayout(jPanel1leftLayout);
        jPanel1leftLayout.setHorizontalGroup(
            jPanel1leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel1leftLayout.setVerticalGroup(
            jPanel1leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1leftLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jPanel2right.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2rightMouseClicked(evt);
            }
        });

        jLabel1Close.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel1Close.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1Close.setText("x");
        jLabel1Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1CloseMouseClicked(evt);
            }
        });

        jLabel2Min.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        jLabel2Min.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2Min.setText("—");
        jLabel2Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MinMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setText("Get Started.");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel2.setText("Already have an account?");

        jLabel3HyperlinkSignin.setFont(new java.awt.Font("Inter", 0, 10)); // NOI18N
        jLabel3HyperlinkSignin.setForeground(new java.awt.Color(121, 6, 186));
        jLabel3HyperlinkSignin.setText("Signin");
        jLabel3HyperlinkSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3HyperlinkSigninMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel4.setText("Firstname");

        jTextField_FirstName.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField_FirstName.setText("John");
        jTextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstNameActionPerformed(evt);
            }
        });

        jTextField_LastName.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField_LastName.setText("Doe");

        jLabel5.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel5.setText("Lastname");

        jLabel6.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel6.setText("Birthdate");

        jTextField_Country.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField_Country.setText("Philippines");

        jLabel7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel7.setText("Country");

        jLabel8.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel8.setText("Username");

        jTextField_Username.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField_Username.setText("johndoe3310");

        jLabel10.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel10.setText("Email");

        jTextField_Email.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jTextField_Email.setText("johndoe3310@gmail.com");

        jLabel9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel9.setText("Password");

        jPasswordField_1.setText("jPasswordField1");

        jLabel11.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel11.setText("Confirm Password");

        jPasswordField_2.setText("jPasswordField2");

        jButton_Register.setBackground(new java.awt.Color(121, 6, 186));
        jButton_Register.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register.setText("Signup");
        jButton_Register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseEntered(evt);
            }
        });
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        MovePanel.setBackground(new java.awt.Color(255, 255, 255));
        MovePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovePanelMouseDragged(evt);
            }
        });
        MovePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovePanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MovePanelLayout = new javax.swing.GroupLayout(MovePanel);
        MovePanel.setLayout(MovePanelLayout);
        MovePanelLayout.setHorizontalGroup(
            MovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        MovePanelLayout.setVerticalGroup(
            MovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jRadioButton_Male.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jRadioButton_Male.setSelected(true);
        jRadioButton_Male.setText("Male");

        jRadioButton_Female.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jRadioButton_Female.setText("Female");

        jLabel13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel13.setText("Gender");

        jLabel14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel14.setText("Phone");

        jTextField_PhoneNum.setText("09669879402");
        jTextField_PhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneNumActionPerformed(evt);
            }
        });
        jTextField_PhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneNumKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2rightLayout = new javax.swing.GroupLayout(jPanel2right);
        jPanel2right.setLayout(jPanel2rightLayout);
        jPanel2rightLayout.setHorizontalGroup(
            jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2rightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MovePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2Min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1Close)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2rightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2rightLayout.createSequentialGroup()
                            .addComponent(jRadioButton_Male)
                            .addGap(32, 32, 32)
                            .addComponent(jRadioButton_Female)
                            .addGap(227, 227, 227))
                        .addComponent(jTextField_PhoneNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2rightLayout.createSequentialGroup()
                                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPasswordField_1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel9)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_Country)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField_Email)
                                    .addComponent(jPasswordField_2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13)
                    .addGroup(jPanel2rightLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3HyperlinkSignin))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2rightLayout.createSequentialGroup()
                        .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(54, 54, 54))
        );
        jPanel2rightLayout.setVerticalGroup(
            jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2rightLayout.createSequentialGroup()
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2rightLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Close)
                            .addComponent(jLabel2Min)))
                    .addComponent(MovePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3HyperlinkSignin))
                .addGap(18, 18, 18)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Male)
                    .addComponent(jRadioButton_Female)
                    .addComponent(jTextField_PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Country)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2rightMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2rightMouseClicked

    private void jLabel2MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MinMouseClicked
            // Check for a mouse click event (e.g., a left mouse button click)
        if (evt.getButton() == MouseEvent.BUTTON1) {
            // Minimize the JFrame
            setExtendedState(JFrame.ICONIFIED);
        }
    }//GEN-LAST:event_jLabel2MinMouseClicked

    private void jLabel1CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1CloseMouseClicked

    private void jLabel3HyperlinkSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3HyperlinkSigninMouseClicked
        // Assuming you have a login form instance named "loginForm"
        login loginForm = new login();

        // Make the login form visible
        loginForm.setVisible(true);

        // Close or hide the current form if necessary
        this.dispose(); // Close the current form
    }//GEN-LAST:event_jLabel3HyperlinkSigninMouseClicked

    private int xMouse,yMouse;
    
    private void MovePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMousePressed
        // JFrame MouseListener Event - Mouse Pressed
        // Get X and Y coordinate values
        xMouse = evt.getX();
        yMouse = evt.getY();   
    }//GEN-LAST:event_MovePanelMousePressed

    private void MovePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovePanelMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_MovePanelMouseDragged

    private void jButton_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RegisterMouseEntered

    private void jTextField_PhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneNumActionPerformed

    private void jTextField_PhoneNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneNumKeyTyped
        char c = evt.getKeyChar();
    
        // Check if the typed character is a digit (0-9)
        if (!Character.isDigit(c)) {
            evt.consume(); // Consume the event to prevent the character from being entered
        }
    }//GEN-LAST:event_jTextField_PhoneNumKeyTyped

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        
        String fname = jTextField_FirstName.getText();
        String lname = jTextField_LastName.getText();
        String gender = "Male";
        String phonenum = jTextField_PhoneNum.getText();
        String country = jTextField_Country.getText();
        String username = jTextField_Username.getText();
        String email = jTextField_Email.getText();
        String pass1 = String.valueOf(jPasswordField_1.getPassword());
        String pass2 = String.valueOf(jPasswordField_2.getPassword());

        // Get the selected birth date from the jDateChooser
        Date selectedBirthDate = jDateChooser.getDate();

        if (jRadioButton_Female.isSelected()) {
            gender = "Female";
        }

        if (verifyFields()) {
            try {
                if (!checkUsername(username)) {
                    PreparedStatement ps;
                    ResultSet rs;
                    String registerUserQuery = "INSERT INTO `users`(`username`, `password`, `firstname`, `lastname`, `gender`, `phonenum`, `country`, `email`, `birthdate`) VALUES (?,?,?,?,?,?,?,?,?)";

                    try {
                        // Convert selectedBirthDate to MySQL DATE format
                        SimpleDateFormat mysqlDateFormat = new SimpleDateFormat("yyyy-MM-dd");
                        String mysqlBirthDate = mysqlDateFormat.format(selectedBirthDate);

                        ps = My_CNX.getConnection().prepareStatement(registerUserQuery);
                        ps.setString(1, username);
                        ps.setString(2, pass1);
                        ps.setString(3, fname);
                        ps.setString(4, lname);
                        ps.setString(5, gender);
                        ps.setString(6, phonenum);
                        ps.setString(7, country);
                        ps.setString(8, email);
                        ps.setString(9, mysqlBirthDate);

                        int rowsAffected = ps.executeUpdate();
                        System.out.println("Rows affected: " + rowsAffected); // Debug statement

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "Account has been created successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Account creation failed.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        ex.printStackTrace(); // Log SQL exceptions
                        Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace(); // Log SQL exceptions
                Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jTextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstNameActionPerformed

    public boolean verifyFields() {
    boolean isValid = true; // Assume all fields are valid initially

        // Define an array of text fields to check
        JTextField[] textFields = {
            jTextField_FirstName,
            jTextField_LastName,
            jTextField_PhoneNum,
            jTextField_Country,
            jTextField_Username,
            jTextField_Email
        };

        // Check if any text field is empty
        for (JTextField textField : textFields) {
            if (textField.getText().isEmpty()) {
                isValid = false;
                // Handle the error or display an error message for the empty field (e.g., "First name is required.")
            }
        }

        // Check if passwords match
        String pass1 = String.valueOf(jPasswordField_1.getPassword());
        String pass2 = String.valueOf(jPasswordField_2.getPassword());

        if (pass1.isEmpty() || pass2.isEmpty()) {
            isValid = false;
            // Handle the error or display an error message for the password fields (e.g., "Both passwords are required.")
        } else if (!pass1.equals(pass2)) {
            isValid = false;
            // Handle the error or display an error message for non-matching passwords (e.g., "Passwords do not match.")
        }

        // Check if one of the radio buttons is selected
        if (!jRadioButton_Male.isSelected() && !jRadioButton_Female.isSelected()) {
            isValid = false;
            // Handle the error or display an error message for radio buttons (e.g., "Please select a gender.")
        }

        // Check if a birthdate is selected
        if (jDateChooser.getDate() == null) {
            isValid = false;
            // Handle the error or display an error message for the birthdate (e.g., "Please select a birthdate.")
        }

        // You can add more validation checks for other fields as needed

        return isValid;
    }

    // create a function if the username already exists in the database
    public boolean checkUsername(String username) throws SQLException {
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `users` WHERE `username` = ?";
        
        try {
            
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            
            if (rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This username is Already Taken, Choose Another One", "Username Failed", 2);
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return username_exist;    
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MovePanel;
    private javax.swing.JButton jButton_Register;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1Close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Min;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3HyperlinkSignin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1left;
    private javax.swing.JPanel jPanel2right;
    private javax.swing.JPasswordField jPasswordField_1;
    private javax.swing.JPasswordField jPasswordField_2;
    private javax.swing.JRadioButton jRadioButton_Female;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JTextField jTextField_Country;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_PhoneNum;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
